# Generated by Django 5.2.13 on 2026-05-11 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_subjectoffering_working_day_time_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicperiod',
            name='schedule_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
