# Generated by Django 5.2.14 on 2026-05-14 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_subject_class_type_item'),
        ('core', '0006_subjectoffering_student_count'),
    ]

    operations = [
    ]
