# Generated by Django 5.2.13 on 2026-05-19 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_merge_20260514_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicperiod',
            name='is_schedule_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='academicperiod',
            name='schedule_published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='user_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_profile', to='core.userprofile'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='class_type_item',
            field=models.ForeignKey(blank=True, limit_choices_to={'catalog_type': 'class_type'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='core.catalogitem'),
        ),
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core.userprofile')),
                ('subject_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_enrollments', to='core.subjectoffering')),
            ],
            options={
                'ordering': ['student__last_name', 'student__first_name', 'subject_offering_id'],
                'constraints': [models.UniqueConstraint(fields=('student', 'subject_offering'), name='unique_student_enrollment')],
            },
        ),
    ]
