from django.urls import path
from rest_framework_simplejwt.views import TokenRefreshView

from .views import (
    AdminOnlyAPIView,
    AcademicPeriodDetailAPIView,
    AcademicPeriodListCreateAPIView,
    AcademicProgramDetailAPIView,
    AcademicProgramListCreateAPIView,
    CampusDetailAPIView,
    CampusListCreateAPIView,
    CatalogItemDetailAPIView,
    CatalogItemListCreateAPIView,
    ClassroomDetailAPIView,
    ClassroomListCreateAPIView,
    CourseDetailAPIView,
    CourseGroupDetailAPIView,
    CourseGroupListCreateAPIView,
    CourseListCreateAPIView,
    LoginAPIView,
    LogoutAPIView,
    MasterDataImportAPIView,
    MeAPIView,
    RoleListAPIView,
    SpaceTypeDetailAPIView,
    SpaceTypeListCreateAPIView,
    SubjectDetailAPIView,
    SubjectListCreateAPIView,
    SubjectGroupDetailAPIView,
    SubjectGroupListCreateAPIView,
    SubjectOfferingDetailAPIView,
    SubjectOfferingListCreateAPIView,
    TeacherDetailAPIView,
    TeacherListCreateAPIView,
    TimeSlotDetailAPIView,
    TimeSlotListCreateAPIView,
    UserDetailAPIView,
    UserListCreateAPIView,
    WorkingDayDetailAPIView,
    WorkingDayListCreateAPIView,
    health_check,
)

urlpatterns = [
    path("health/", health_check, name="health-check"),
    path("auth/login/", LoginAPIView.as_view(), name="auth-login"),
    path("auth/refresh/", TokenRefreshView.as_view(), name="auth-refresh"),
    path("auth/logout/", LogoutAPIView.as_view(), name="auth-logout"),
    path("auth/me/", MeAPIView.as_view(), name="auth-me"),
    path("auth/admin-only/", AdminOnlyAPIView.as_view(), name="auth-admin-only"),
    path("roles/", RoleListAPIView.as_view(), name="roles-list"),
    path("users/", UserListCreateAPIView.as_view(), name="users-list-create"),
    path("users/<int:user_profile_id>/", UserDetailAPIView.as_view(), name="users-detail"),
    path(
        "config/periods/",
        AcademicPeriodListCreateAPIView.as_view(),
        name="config-periods-list-create",
    ),
    path(
        "config/periods/<int:config_id>/",
        AcademicPeriodDetailAPIView.as_view(),
        name="config-periods-detail",
    ),
    path(
        "config/working-days/",
        WorkingDayListCreateAPIView.as_view(),
        name="config-working-days-list-create",
    ),
    path(
        "config/working-days/<int:config_id>/",
        WorkingDayDetailAPIView.as_view(),
        name="config-working-days-detail",
    ),
    path(
        "config/time-slots/",
        TimeSlotListCreateAPIView.as_view(),
        name="config-time-slots-list-create",
    ),
    path(
        "config/time-slots/<int:config_id>/",
        TimeSlotDetailAPIView.as_view(),
        name="config-time-slots-detail",
    ),
    path(
        "config/space-types/",
        SpaceTypeListCreateAPIView.as_view(),
        name="config-space-types-list-create",
    ),
    path(
        "config/space-types/<int:config_id>/",
        SpaceTypeDetailAPIView.as_view(),
        name="config-space-types-detail",
    ),
    path(
        "catalogs/<str:catalog_type>/",
        CatalogItemListCreateAPIView.as_view(),
        name="catalogs-list-create",
    ),
    path(
        "catalogs/<str:catalog_type>/<int:config_id>/",
        CatalogItemDetailAPIView.as_view(),
        name="catalogs-detail",
    ),
    path(
        "imports/master-data/",
        MasterDataImportAPIView.as_view(),
        name="imports-master-data",
    ),
    path("master-data/campuses/", CampusListCreateAPIView.as_view(), name="campuses-list-create"),
    path("master-data/campuses/<int:item_id>/", CampusDetailAPIView.as_view(), name="campuses-detail"),
    path(
        "master-data/programs/",
        AcademicProgramListCreateAPIView.as_view(),
        name="programs-list-create",
    ),
    path(
        "master-data/programs/<int:item_id>/",
        AcademicProgramDetailAPIView.as_view(),
        name="programs-detail",
    ),
    path("master-data/teachers/", TeacherListCreateAPIView.as_view(), name="teachers-list-create"),
    path("master-data/teachers/<int:item_id>/", TeacherDetailAPIView.as_view(), name="teachers-detail"),
    path("master-data/courses/", CourseListCreateAPIView.as_view(), name="courses-list-create"),
    path("master-data/courses/<int:item_id>/", CourseDetailAPIView.as_view(), name="courses-detail"),
    path(
        "master-data/course-groups/",
        CourseGroupListCreateAPIView.as_view(),
        name="course-groups-list-create",
    ),
    path(
        "master-data/course-groups/<int:item_id>/",
        CourseGroupDetailAPIView.as_view(),
        name="course-groups-detail",
    ),
    path("master-data/classrooms/", ClassroomListCreateAPIView.as_view(), name="classrooms-list-create"),
    path(
        "master-data/classrooms/<int:item_id>/",
        ClassroomDetailAPIView.as_view(),
        name="classrooms-detail",
    ),
    path(
        "programming/subjects/",
        SubjectListCreateAPIView.as_view(),
        name="programming-subjects-list-create",
    ),
    path(
        "programming/subjects/<int:config_id>/",
        SubjectDetailAPIView.as_view(),
        name="programming-subjects-detail",
    ),
    path(
        "programming/subject-groups/",
        SubjectGroupListCreateAPIView.as_view(),
        name="programming-subject-groups-list-create",
    ),
    path(
        "programming/subject-groups/<int:config_id>/",
        SubjectGroupDetailAPIView.as_view(),
        name="programming-subject-groups-detail",
    ),
    path(
        "programming/subject-offerings/",
        SubjectOfferingListCreateAPIView.as_view(),
        name="programming-subject-offerings-list-create",
    ),
    path(
        "programming/subject-offerings/<int:subject_offering_id>/",
        SubjectOfferingDetailAPIView.as_view(),
        name="programming-subject-offerings-detail",
    ),
]
